site_name: 程序员的Cookbook
theme:
  name: material
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  custom_dir: overrides
  language: zh
  font:
    text: Noto Serif Simplified Chinese
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tooltips

plugins:
  - search
  - blog:
      blog_toc: true
      pagination_per_page: 10
      pagination_if_single_page: false
      pagination_keep_content: true
      archive_date_format: yyyy/MMMM
  - tags

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: blog/about.md

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - abbr
  - md_in_html
  - attr_list
  - footnotes
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-V25PBTCZMN
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zyfjeff

copyright: Copyright &copy; 2024 - 2025 程序员的Cookbook

site_url: https://zyfjeff.github.io
