cc_binary(
    name = "asbeil_string",
    srcs = ["abseil_string.cc"],
    deps = [
        "@com_google_absl//absl/strings:strings",
    ],
)

cc_binary(
    name = "asbeil_container",
    srcs = ["abseil_container.cc"],
    deps = [
        "@com_google_absl//absl/container:btree",
    ],
)

