authors:
  jeff:
    name: jeff        # Author name
    description: Creator      # Author description
    avatar: https://avatars.githubusercontent.com/u/8816403         # Author avatar
    url: https://github.com/zyfjeff            # Author website URL